# MIMIC Contrastive Learning with MedCLIP

# Model configuration
model:
  model_type: "medclip"
  checkpoint: "./pretrained/medclip-vit"
  
# Dataset configuration
dataset:
  dataset_name: "mimic"
  data_root: "./local_data/mimic"
  batch_size: 32
  num_workers: 8
  shuffle: true
  
# Training configuration
training:
  num_epochs: 50
  save_every: 5
  eval_every: 2
  
# Loss configuration
loss:
  type: "contrastive"
  temperature: 0.07
  
# Optimizer configuration
optimizer:
  type: "adam"
  lr: 1e-4
  weight_decay: 1e-6
  
# Scheduler configuration
scheduler:
  type: "cosine"
  warmup_epochs: 5
  min_lr: 1e-6
  
# Output settings
output:
  save_checkpoints: true
  checkpoint_dir: "./checkpoints/mimic_medclip_contrastive"
  save_results: true
  results_dir: "./results/mimic_medclip_contrastive"
