# RSNA Zero-shot Classification with MedCLIP

# Model configuration
model:
  model_type: "biomedclip"
  checkpoint: null
  
# Dataset configuration
dataset:
  dataset_name: "rsna"
  data_root: "local_data/rsna"
  batch_size: 64
  num_workers: 4
  shuffle: false  
  
# Evaluation configuration
evaluations:
  rsna_zero_shot:
    type: "zero_shot"
    class_names: ["Normal", "Pneumonia"]
    mode: "binary"
    templates:
      - "this is a chest x-ray showing {}"
      - "a chest radiograph with {}"
      - "chest x-ray image of {}"
    top_k: [1, 2]
    return_predictions: true
    
# Output settings
output:
  save_results: true
  results_dir: "./results/rsna_biomedclip_zero_shot"
